[package]
name = "more-money"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
persi-ds = { git = "https://github.com/kod-kristoff/persi-ds" }
